<script setup lang="ts">
import {
  Download,
  Plus,
  Search,
  Link,
  LibraryBig,
  Leaf,
  Settings,
  ListVideo,
  BookOpen,
  Heart,
  Play,
  Pause,
  X,
  Check,
  ChevronRight,
  ChevronDown,
  LoaderCircle,
  ArrowUpRight,
  CircleHelp,
  Folder,
  FileText,
  Trash2,
  RotateCcw,
  Headphones,
  Clock,
  SlidersHorizontal,
  ExternalLink,
  Sparkles,
  Video,
  HardDrive,
  ShieldCheck,
  Zap,
  Copy,
  Menu,
  CheckCheck,
  Bookmark,
  ArrowDownToLine,
  Upload,
  CircleCheck,
  Sun,
  LogOut,
  TriangleAlert,
  GitFork,
} from '@lucide/vue'
defineProps<{ name: string; size?: number }>()
const icons: Record<string, unknown> = {
  download: Download,
  plus: Plus,
  search: Search,
  link: Link,
  library: LibraryBig,
  leaf: Leaf,
  settings: Settings,
  queue: ListVideo,
  book: BookOpen,
  heart: Heart,
  play: Play,
  pause: Pause,
  x: X,
  check: Check,
  right: ChevronRight,
  down: ChevronDown,
  loader: LoaderCircle,
  arrow: ArrowUpRight,
  help: CircleHelp,
  folder: Folder,
  file: FileText,
  trash: Trash2,
  retry: RotateCcw,
  headphones: Headphones,
  clock: Clock,
  sliders: SlidersHorizontal,
  external: ExternalLink,
  sparkles: Sparkles,
  video: Video,
  storage: HardDrive,
  shield: ShieldCheck,
  zap: Zap,
  copy: Copy,
  menu: Menu,
  github: GitFork,
  checks: CheckCheck,
  bookmark: Bookmark,
  save: ArrowDownToLine,
  upload: Upload,
  circlecheck: CircleCheck,
  sun: Sun,
  logout: LogOut,
  alert: TriangleAlert,
}
</script>
<template>
  <component :is="icons[name] || icons.video" :size="size || 20" :stroke-width="1.7" aria-hidden="true" />
</template>
